dependencies: base
library:
  source-dirs:
    - src
  dependencies:
    - containers
    - mtl
    - ecstasy
    - random
executables:
  hautochess-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hautochess
      - random
